### ISSUE TITLE
What is success?

### ISSUE THREAD

**Issue by alecthegeek** [PaperCutSoftware/web-services-api-dot-net-core#5]
I wanted to make some suggestions on things we could deliver. Hopefully that will give us some focus

1. Make it easy to use the PaperCut NG/MG web services API from Powershell and .NET languages (e.g. C#) by replacing, or updating, the current .NET Framework tools (Cook Computing XML-RPC lib and serverproxy.cs)

2. Provide some easy to use Powershell commands to install any required libraries etc

3. Track any changes PaperCut may make to the web services API.

If people can agree on these goals then we can start to create some tasks and move forward.

**Comment by Joffcom** [comment]
Looks good to me, I would also suggest maybe compiling a DLL with every release as well for the API so those who just want to get stuck in without having to compile themselves can.

**Comment by alecthegeek** [comment]
So I think we hit objective 1 and 3

Just leaves turning it into a nice PowerShell module

I'm going to close this issue and open another one for PowerShell module which I think will interest @theaquamarine.
